### ISSUE TITLE
Decompression a folder which name is chinese,the folder name will becomes garbled

### ISSUE THREAD

**Issue by yuxiaoyan1205** [kevva/decompress#54] opened 2017-04-27 07:39 UTC
Use Apple computer to compress a folder，this folder‘s name is Chinese ,then use this to extract down, the folder name becomes garbled

**Comment by kevva** [comment] 2017-05-18 22:19
Probably duplicate of https://github.com/kevva/decompress/issues/47.

**Closed by kevva** 2017-05-18 22:19 UTC
